apiVersion: v2
name: ngrok-operator
description: A Kubernetes ingress controller built using ngrok.
version: 0.14.0
appVersion: 0.12.0
keywords:
  - ngrok
  - networking
  - ingress
  - edge
  - api gateway
home: https://ngrok.com
sources:
  - https://github.com/ngrok/ngrok-operator
icon: https://ngrok.github.io/ngrok-operator/ngrok-favicon.svg
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
